### ISSUE TITLE
Manifest unknown

### ISSUE THREAD

**Issue by zerzavot** [justb4/docker-pgbackup#2]
Hi,
When i tried to backup from Postgre 12 ,i used justb4/pgbackup:12 image as u mentioned. However, a manifest unknown error message came up. How can i solve this problem? 
I have attached my compose file and error message.

![image](https://user-images.githubusercontent.com/50207648/131457940-66bba313-a3e5-4137-9b4f-2a2395938b27.png)
![image](https://user-images.githubusercontent.com/50207648/131458258-607e55e0-952e-4cc9-872f-16827a0562c5.png)

**Comment by zerzavot** [comment]
9.6 ,10 and 11 work fine. But there is a problem with 12 and 13
![image](https://user-images.githubusercontent.com/50207648/131459368-b4918c77-1ff5-41e0-927b-d89a8c0a3d6f.png)

**Comment by justb4** [comment]
Versions 12 and 13 are not yet in DockerHub. DockerHub also changed policies for automated builds on free account.
For now the best option is to build yourself, e.g. see `git/13/build.sh`.
I will investigate to build/push via GitHub actions to DockerHub.

**Comment by zerzavot** [comment]
Hi dayı,

I sincerely appreciate ur help with this problem. When i followed your advice (building from your git repo) the manifest problem still exists. After some research and Tolga Abi's help I found a solution. 
We should add this line in ur Dockerfile `RUN apk add py3-pip`


Thank u very much for this clean code and this amazing image!

![image](https://user-images.githubusercontent.com/50207648/131720678-7ff4b81d-e410-406b-85f1-60fa22f9aebe.png)

**Comment by justb4** [comment]
Ok, yes, I see that same issue mentioned:
https://medium.com/@ssorcnafets/apk-add-python3-py3-pip-c3f91cd3d1e1

So at least will add your suggestion `py3-pip`.

**Comment by justb4** [comment]
Revised the builds: all versions: 9.6, 10, 11, 12, 13 should be [available from DockerHub](https://hub.docker.com/repository/docker/justb4/pgbackup) @Zerzavot can you verify?

**Comment by zerzavot** [comment]
Everything is working without any problem. Thank u!
![image](https://user-images.githubusercontent.com/50207648/131970817-0166cdf0-8dfa-4f10-89a2-54160902eacf.png)
